license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

logoFile="assets/steelmeridian/logo.png"
logoBlur=false

authors="ZettaBite4031, Tori, Mira"
credits="Inspired by Factorio by Wube Software."

description='''
Steel Meridian is a large-scale overhaul mod that adapts Factorio's factory-building gameplay to Minecraft's three-dimensional world.

Build sprawling automated production lines, mine and process resources, route items through belts and inserters, develop electrical and fluid networks, research new technologies, construct rail systems, deploy logistics and construction robots, and defend an industrial world capable of growing to enormous scale.

The goal is not simply to add Factorio-inspired machines to Minecraft, but to preserve the systems, progression, and engineering philosophy that make Factorio work while embracing the possibilities of a fully 3D Minecraft world.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"